#!/usr/bin/env python3
"""
Emit a text tree of the repository, excluding bulky or generated paths.

Usage:
  python scripts/repo_inventory.py
  python scripts/repo_inventory.py --out docs/generated/repo_inventory.txt

Used for CTO / onboarding documentation and drift detection.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

# Directory names to skip entirely (any depth).
SKIP_DIR_NAMES: frozenset[str] = frozenset(
    {
        ".git",
        ".venv",
        "venv",
        "__pycache__",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        "node_modules",
        ".next",
        "dist",
        "build",
        ".eggs",
    }
)

# Skip if path segment matches these prefixes (e.g. foo.egg-info).
SKIP_DIR_PREFIXES: tuple[str, ...] = (".egg-info",)


def _skip_dir(name: str) -> bool:
    if name in SKIP_DIR_NAMES:
        return True
    if name.endswith(SKIP_DIR_PREFIXES):
        return True
    return False


def walk_tree(root: Path, max_depth: int | None = None) -> list[str]:
    lines: list[str] = []

    def _walk(current: Path, prefix: str, depth: int) -> None:
        if max_depth is not None and depth > max_depth:
            return
        try:
            entries = sorted(current.iterdir(), key=lambda p: (not p.is_dir(), p.name.lower()))
        except PermissionError:
            lines.append(f"{prefix}[permission denied]")
            return
        dirs = [e for e in entries if e.is_dir() and not _skip_dir(e.name)]
        files = [e for e in entries if e.is_file()]
        all_items = dirs + files
        for i, p in enumerate(all_items):
            is_last = i == len(all_items) - 1
            branch = "└── " if is_last else "├── "
            lines.append(f"{prefix}{branch}{p.name}")
            if p.is_dir():
                extension = "    " if is_last else "│   "
                _walk(p, prefix + extension, depth + 1)

    lines.append(str(root.resolve()))
    _walk(root, "", 1)
    return lines


def walk_tree_json(root: Path, max_depth: int | None = None) -> dict:
    """Nested directory tree as JSON-serializable dicts."""

    def _node(path: Path, depth: int) -> dict:
        name = path.name or str(path)
        if path.is_file():
            return {"type": "file", "name": name}
        if max_depth is not None and depth > max_depth:
            return {"type": "dir", "name": name, "children": [], "truncated": True}
        try:
            entries = sorted(path.iterdir(), key=lambda p: (not p.is_dir(), p.name.lower()))
        except PermissionError:
            return {"type": "dir", "name": name, "error": "permission_denied", "children": []}
        children: list[dict] = []
        for e in entries:
            if e.is_dir() and _skip_dir(e.name):
                continue
            children.append(_node(e, depth + 1))
        return {"type": "dir", "name": name, "children": children}

    return {
        "format": "agent-cloud.repo_inventory.v1",
        "root": str(root.resolve()),
        "skip_dir_names": sorted(SKIP_DIR_NAMES),
        "tree": _node(root, 1),
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--root",
        type=Path,
        default=Path(__file__).resolve().parents[1],
        help="Repository root (default: parent of scripts/)",
    )
    parser.add_argument(
        "--max-depth",
        type=int,
        default=None,
        help="Optional max directory depth from root",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=None,
        help="Write output to this file (UTF-8); default: stdout",
    )
    parser.add_argument(
        "--format",
        choices=("text", "json"),
        default="text",
        help="text: ASCII tree (default); json: nested tree object",
    )
    args = parser.parse_args()
    root: Path = args.root
    if not root.is_dir():
        raise SystemExit(f"Not a directory: {root}")

    if args.format == "json":
        payload = walk_tree_json(root, max_depth=args.max_depth)
        payload["generated_by"] = "scripts/repo_inventory.py"
        payload["cwd"] = os.getcwd()
        text = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
        if args.out:
            args.out.parent.mkdir(parents=True, exist_ok=True)
            args.out.write_text(text, encoding="utf-8")
            print(f"Wrote {args.out} (json)")
        else:
            print(text, end="")
        return

    tree = walk_tree(root, max_depth=args.max_depth)
    text = "\n".join(tree) + "\n"
    text = f"# Generated by scripts/repo_inventory.py\n# cwd={os.getcwd()}\n\n" + text

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(text, encoding="utf-8")
        print(f"Wrote {args.out} ({len(tree)} lines)")
    else:
        print(text, end="")


if __name__ == "__main__":
    main()
